export const SEND_MONEY_USE_CASE = Symbol('SEND_MONEY_USE_CASE');
export const LOAD_ACCOUNT_PORT = Symbol('LOAD_ACCOUNT_PORT');
export const UPDATE_ACCOUNT_STATE_PORT = Symbol('UPDATE_ACCOUNT_STATE_PORT');
export const GET_ACCOUNT_BALANCE_USE_CASE = Symbol(
  'GET_ACCOUNT_BALANCE_USE_CASE',
);
